apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "holdfast.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "holdfast.backend.labels" . | nindent 4 }}
data:
  PSQL_HOST: {{ include "holdfast.postgres.host" . | quote }}
  PSQL_PORT: {{ include "holdfast.postgres.port" . | quote }}
  PSQL_USER: {{ include "holdfast.postgres.user" . | quote }}

  STORAGE_ANALYTICS: {{ .Values.storage.analytics | quote }}

  REACT_APP_PUBLIC_GRAPH_URI: {{ .Values.publicGraphUri | quote }}
  REACT_APP_PRIVATE_GRAPH_URI: {{ .Values.privateGraphUri | quote }}
  REACT_APP_FRONTEND_URI: {{ .Values.publicUrl | quote }}
  COLLECTOR_OTLP_ENDPOINT: {{ .Values.collectorOtlpEndpoint | quote }}

  AUTH_MODE: {{ .Values.auth.mode | quote }}
