version: "2"

# options for analysis running
run:
    timeout: 5m

# output configuration options
output:
    # sorts results by: filepath, line and column
    sort-results: true

linters:
    exclusions:
        paths:
            - private-graph/graph/generated
            - public-graph/graph/generated
    enable:
        - errcheck
        - gosimple
        - govet
        - ineffassign
        - staticcheck
        - unused
        - depguard
        - exhaustruct

# all available settings of specific linters
linters-settings:
    staticcheck:
        checks: ['all']

    exhaustruct:
        include:
            - 'backend/alerts'

    depguard:
        rules:
            main:
                list-mode: lax
                deny:
                    - pkg: 'log'
                      desc: 'logging is allowed only by github.com/sirupsen/logrus'
