{
 "title": "Highlight Plugin Insights",
 "tags": [
  "observability",
  "holdfast"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Datasource",
    "query": "highlightinc-highlight-datasource"
   }
  ]
 },
 "panels": [
  { "title": "Release", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Sessions",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketBy": "None",
     "bucketCount": 50,
     "column": "duration",
     "limit": 5,
     "limitAggregator": "Count",
     "limitColumn": "duration",
     "metric": "Count",
     "table": "sessions"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketBy": "None",
     "bucketCount": 50,
     "column": "duration",
     "limit": 5,
     "limitAggregator": "Count",
     "limitColumn": "duration",
     "metric": "Count",
     "table": "errors"
    }
   ]
  },
  {
   "title": "App Releases",
   "type": "state-timeline",
   "description": "Service versions.",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "bucketBy": "Timestamp",
     "bucketCount": 50,
     "column": "duration",
     "groupBy": [ "service_version" ],
     "limit": 3,
     "limitAggregator": "Count",
     "limitColumn": "duration",
     "metric": "Count",
     "queryText": "service_version exists",
     "table": "logs"
    },
    {
     "bucketBy": "Timestamp",
     "bucketCount": 50,
     "column": "duration",
     "groupBy": [ "service_version" ],
     "limit": 3,
     "limitAggregator": "Count",
     "limitColumn": "duration",
     "metric": "Count",
     "queryText": "service_version exists",
     "table": "sessions"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Users on Highlight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketBy": "Timestamp",
     "bucketCount": 48,
     "column": "duration",
     "groupBy": [ "email" ],
     "limit": 10,
     "limitAggregator": "Count",
     "limitColumn": "duration",
     "metric": "Count",
     "queryText": "email exists",
     "table": "sessions"
    }
   ]
  },
  {
   "title": "Average Time Spent by User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketBy": "Timestamp",
     "bucketCount": 48,
     "column": "active_length",
     "groupBy": [ "email" ],
     "limit": 10,
     "limitAggregator": "Count",
     "limitColumn": "duration",
     "metric": "Avg",
     "queryText": "email exists",
     "table": "sessions"
    }
   ]
  },
  {
   "title": "Users on Highlight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketBy": "Timestamp",
     "bucketCount": 48,
     "column": "duration",
     "limit": 10,
     "limitAggregator": "Count",
     "limitColumn": "duration",
     "metric": "Count",
     "table": "sessions"
    }
   ]
  },
  {
   "title": "Most Visited Pages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "sessions" } },
   "targets": [
    {
     "bucketBy": "Timestamp",
     "bucketCount": 48,
     "column": "duration",
     "groupBy": [ "visited-url" ],
     "limit": 5,
     "limitAggregator": "Count",
     "limitColumn": "duration",
     "metric": "Count",
     "queryText": "visited-url exists",
     "table": "sessions"
    }
   ]
  },
  {
   "title": "Sessions with User Frustration",
   "type": "timeseries",
   "description": "Sessions with rage clicks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "sessions" } },
   "targets": [
    {
     "bucketBy": "Timestamp",
     "bucketCount": 48,
     "column": "duration",
     "limit": 10,
     "limitAggregator": "Count",
     "limitColumn": "duration",
     "metric": "Count",
     "queryText": "has_rage_clicks=true",
     "table": "sessions"
    }
   ]
  },
  {
   "title": "Session H.track Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketBy": "Timestamp",
     "bucketCount": 48,
     "column": "duration",
     "groupBy": [ "event" ],
     "limit": 10,
     "limitAggregator": "Count",
     "limitColumn": "duration",
     "metric": "Count",
     "table": "sessions"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Errors by Message",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "errors" } },
   "targets": [
    {
     "bucketBy": "Timestamp",
     "bucketCount": 50,
     "column": "duration",
     "groupBy": [ "event" ],
     "limit": 10,
     "limitAggregator": "Count",
     "limitColumn": "duration",
     "metric": "Count",
     "table": "errors"
    }
   ]
  },
  {
   "title": "Errors by Browser",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "errors" } },
   "targets": [
    {
     "bucketBy": "Timestamp",
     "bucketCount": 50,
     "column": "duration",
     "groupBy": [ "browser" ],
     "limit": 10,
     "limitAggregator": "Count",
     "limitColumn": "duration",
     "metric": "Count",
     "table": "errors"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Logs by Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "lines" } },
   "targets": [
    {
     "bucketBy": "Timestamp",
     "bucketCount": 50,
     "column": "duration",
     "groupBy": [ "level" ],
     "limit": 10,
     "limitAggregator": "Count",
     "limitColumn": "duration",
     "metric": "Count",
     "table": "logs"
    }
   ]
  },
  {
   "title": "Top Services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "lines" } },
   "targets": [
    {
     "bucketBy": "Timestamp",
     "bucketCount": 50,
     "column": "duration",
     "groupBy": [ "service_name" ],
     "limit": 10,
     "limitAggregator": "Count",
     "limitColumn": "duration",
     "metric": "Count",
     "queryText": "service_name exists",
     "table": "logs"
    },
    {
     "bucketBy": "Timestamp",
     "bucketCount": 50,
     "column": "duration",
     "groupBy": [ "environment" ],
     "limit": 10,
     "limitAggregator": "Count",
     "limitColumn": "duration",
     "metric": "Count",
     "queryText": "environment exists",
     "table": "logs"
    }
   ]
  },
  { "title": "Network Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Slowest APIs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "bucketBy": "Timestamp",
     "bucketCount": 24,
     "column": "duration",
     "groupBy": [ "http.url" ],
     "limit": 5,
     "limitAggregator": "Count",
     "limitColumn": "duration",
     "metric": "P95",
     "queryText": "http.method exists http.url exists http.url=*api*",
     "table": "traces"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "bucketBy": "Timestamp",
     "bucketCount": 50,
     "column": "Duration",
     "groupBy": [ "http.status_code" ],
     "metric": "Count",
     "queryText": "http.status_code exists http.status_code>399",
     "table": "traces"
    }
   ]
  },
  {
   "title": "Slowest Graphql",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "bucketBy": "Timestamp",
     "bucketCount": 24,
     "column": "duration",
     "groupBy": [ "graphql.operation.name" ],
     "limit": 5,
     "limitAggregator": "Count",
     "limitColumn": "duration",
     "metric": "P95",
     "queryText": "graphql.operation.name exists",
     "table": "traces"
    }
   ]
  },
  {
   "title": "Errors by HTTP Url",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "bucketBy": "Timestamp",
     "bucketCount": 50,
     "column": "Duration",
     "groupBy": [ "http.url" ],
     "metric": "Count",
     "queryText": "http.status_code exists http.status_code>399",
     "table": "traces"
    }
   ]
  },
  {
   "title": "Web Socket Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "messages" } },
   "targets": [
    {
     "bucketBy": "Timestamp",
     "bucketCount": 24,
     "column": "duration",
     "groupBy": [ "http.url" ],
     "limit": 5,
     "limitAggregator": "Count",
     "limitColumn": "duration",
     "metric": "Count",
     "queryText": "ws.message exists",
     "table": "traces"
    }
   ]
  },
  {
   "title": "HTTP Requests by Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "bucketBy": "Timestamp",
     "bucketCount": 50,
     "column": "http.response_content_length",
     "groupBy": [ "graphql.operation.name" ],
     "limit": 10,
     "metric": "Sum",
     "queryText": "http.response_content_length exists http.response_content_length>1000000",
     "table": "traces"
    }
   ]
  }
 ]
}